### ISSUE TITLE
Not so helpful messages

### ISSUE THREAD

**Issue by stormbr** [rfuzzo/plox#21]
When using plox in my openmw setup I get some messages that are very unhelpfull because the do not point to the culprights....

[ERROR plox] [REQUIRES]

[WARN  plox] [CONFLICT]
    already merged into or otherwise replicated by "ldm - choices and consequences".

[WARN  plox] [CONFLICT]
    not compatible with "legion at the siege of firemoth".

[INFO  plox] [NOTE]
    a patch for "legion at the siege of firemoth" and "bcom" is available.      [patch download]( https://www.nexusmods.com/morrowind/mods/52601 )

[INFO  plox] [NOTE]
    ! this mod has a bsa, be sure to register it.

**Comment by rfuzzo** [comment]
hmm, there is no dropdown with "affected mods"?

**Comment by stormbr** [comment]
I am using only the command line  executable;

**Comment by rfuzzo** [comment]
oh I think I know what it is: the CLI only shows that info when using debug log mode. Maybe I should add it to normal indo logging...

**Comment by stormbr** [comment]
Thank you for your great work.
