### ISSUE TITLE
Parser cannot handle omwscripts

### ISSUE THREAD

**Issue by pharispharispharis** [rfuzzo/plox#23]
.omwscripts are a special case in that they are just plain text files rather than the TES3 format but they should be sorted along with the rest of the content files as their order can be relevant (though I doubt there's a real case of that in any mods now). 

plox should not attempt to parse the header of .omwscripts and any predicate that requires access to information in the plugin header ( e.g. DESC ) should always evaluate to false.

EDIT: Another oddity is that they can contain comments which makes the SIZE predicate potentially even more useless for them than it is with plugins

**Comment by rfuzzo** [comment]
hmm right thanks. so the solution is simply to 
- add support for them
- but skip parsing them 
right?
