### ISSUE TITLE
Doesn't seem to work with openmw in linux

### ISSUE THREAD

**Issue by DuendeInexistente** [rfuzzo/plox#26]
small note before anything else: there should be a notice that the "game folder" for openmw means "where openmw.cfg is.". I had to guesstimate that. In linux' case, ~/.config/openmw.

Now for the actual issue. Plox (Both gui and terminal) detect the cfg but aren't listing any esp. The list returns nothing with ``plox list``. The gui just gives me nothing. I tried running with -l trace and didn't get anymore info.

![image](https://github.com/rfuzzo/plox/assets/20157727/98af1dcd-8c3c-4dc9-97f3-d24d2b6c4eb5)

[Here's my cfg in case it's malformed somehow.](https://gist.github.com/DuendeInexistente/6504d623ccd33881873a0f7a05b504e9)

**Comment by rfuzzo** [comment]
Hmm thanks, on Linux is the default config not next to the openmw app?

**Comment by rfuzzo** [comment]
And for the actual issue: Can you check if it works when you manually specify the cfg path with the -c option in the CLI or the plox.toml configuration file for the GUI?

**Comment by DuendeInexistente** [comment]
> Hmm thanks, on Linux is the default config not next to the openmw app?

Well, the *default config* is there, but the actual config that maters (data folders and content files) is completely inside openmw.cfg in the specified path. Users editing default config files and breaking things has historically been a regular source of annoyance for openmw devs.

> Can you check if it works when you manually specify the cfg path with the -c option in the CLI or the plox.toml configuration file for the GUI?
```toml
no_rules_download = true 
log_level = "trace"
log_to_file = true 
config = "/home/cammera/.config/openmw"
game = "OpenMW"
```
Rules already downloaded, no results either.

**Comment by rfuzzo** [comment]
plox checks for existence of the default cfg to deduce the game (if not specified with the --game argument) That's why I was asking

**Comment by rfuzzo** [comment]
Linux should work now, has been tested by some people
