### ISSUE TITLE
useful warning or error?

### ISSUE THREAD

**Issue by abitoftaste** [rfuzzo/plox#27]
10:56:44 [WARN] Malformed Order rule: less than 2 expressions
10:56:44 [DEBUG] (2) plox::parser: Error 'Malformed Order rule: less than 2 expressions' at chunk #504, starting at line: 2614
10:56:44 [DEBUG] (2) plox::parser: [order]
go to jail*.esp

not sure if already just a useful plox warning to ease fixing the order rule or something causing an error in plox sorting (and that should be kept as warning but skipped/ignored on calculating order like MLOX seems to do), so I'm posting it just in case

**Comment by rfuzzo** [comment]
Thanks, it seems to have problems parsing that specific rule. Do you have the whole rule that is in question here? At line 2614?

**Comment by abitoftaste** [comment]
[Order]
ab01GOTYpatch.esp
;JoinAll*.esp

apparently MLOX is able to just ignore it, while PLOX gives a warning in the log (that's good, it should be all commented out) but I am not sure it is just skipping it and keeping processing like MLOX or having problems with it

**Comment by rfuzzo** [comment]
ah right. yeah it is just skipping it. but I will add some tests to confirm. 👍
